language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install -e ."
before_script:
  - pip install -r requirements.dev.txt
script: ./run_tests
